spring:
 datasource:
  url: 'jdbc:h2:file:~/testdb;DB_CLOSE_DELAY=-1;mv_store=false'
  username: sa
  password: sa

englishonly: false

camunda.bpm:
  webapp.application-path: /
  authorization.enabled: true
  generic-properties:
   properties:
    initializeTelemetry: false
    telemetryReporterActivate: false

cawemo:
  enabled: 'false'
  url: '${CAWEMO_URL}'
  apiKey: '${CAWEMO_API_KEY}'
  orgId: '${CAWEMO_ORG_ID}'
  authMode: 'BASIC'
  projectName: 'Customer Onboarding'

server:
  servlet:
    context-path: /camunda
